# Generated by Django 3.2.5 on 2021-07-28 19:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0002_auto_20210728_1326'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='due_date',
            field=models.DateField(blank=True),
        ),
        migrations.AlterField(
            model_name='task',
            name='time_spent',
            field=models.DurationField(null=True),
        ),
    ]
