# Generated by Django 3.2.5 on 2021-07-31 13:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0004_auto_20210730_1243'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='task',
            name='time_spent',
        ),
    ]
