# Generated by Django 3.2.5 on 2021-08-17 14:48

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('user', '0003_crew_date_added'),
        ('project', '0005_remove_task_time_spent'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='task',
            options={'ordering': ('-priority', '-due_date')},
        ),
        migrations.AlterField(
            model_name='project',
            name='crew',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='projects', to='user.crew'),
        ),
        migrations.AlterField(
            model_name='task',
            name='assigned_by',
            field=models.ManyToManyField(blank=True, related_name='user_tasks', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='task',
            name='due_date',
            field=models.DateField(),
        ),
        migrations.AlterField(
            model_name='task',
            name='priority',
            field=models.CharField(choices=[('1', 'Low'), ('2', 'Medium'), ('3', 'High')], default='1', max_length=15),
        ),
    ]
